repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: versioneer.py
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/rapidsai/frigate/
    rev: v0.4.0 #  pre-commit autoupdate  - to keep the version up to date
    hooks:
      - id: frigate
  - repo: local
    hooks:
      - id: check-crd-updates
        name: check-crd-updates
        entry: ci/pre-commit-crd.py v0.14.0
        language: script
        types: [yaml]
        pass_filenames: true
      - id: check-go-generation
        name: check-go-generation
        entry: dask_kubernetes/operator/go_client/hack/regenerate-code.sh
        language: script
        files: ^dask_kubernetes/operator/go_client/pkg/apis/.*\.go$
        exclude: ^dask_kubernetes/operator/go_client/pkg/apis/.*zz_generated.*\.go$
        pass_filenames: false
      - id: lint-go-code
        name: lint-go-code
        entry: dask_kubernetes/operator/go_client/hack/lint.sh
        language: script
        files: ^dask_kubernetes/operator/go_client/.*\.go$
        pass_filenames: false
      - id: build-go-code
        name: build-go-code
        entry: golang:1.19.10-bookworm bash -c 'GOCACHE=/src/.cache go build ./...'
        language: docker_image
        files: |
          (?x)^(
            go\.mod
            |go\.sum
            |dask_kubernetes/operator/go_client/.*\.go
          )$
        pass_filenames: false