version: 2

jobs:
  build:
    machine: true
    environment:
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      CHANGE_MINIKUBE_NONE_USER: true
      PYTHON: "3.7"
      ENV_NAME: "dask-kubernetes-test"

    steps:
      - checkout
      - run:
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.8.4/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      # Use minikube v0.25.2 as v0.26.0 requires systemd to manage the daemons which
      # is not available in the Ubuntu 14.04 image used by Circle CI with the
      # "machine: true" option.
      - run:
          command: |
            curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/v0.25.2/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          command: |
            sudo -E minikube start --vm-driver=none --extra-config=kubelet.MaxPods=20
      - run:
          command: |
            sudo -E minikube addons enable kube-dns
      - run:
          command: |
            sudo -E minikube update-context
      - run:
          command: |
            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until sudo kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
      - run:
          command: |
            sudo kubectl cluster-info
      - run:
          command: |
            sudo kubectl run circleci-example --image=nginx
            sudo kubectl expose deployment circleci-example --port 80 --type=ClusterIP --name=circleci-example
      - run:
          command: |
            sudo kubectl get deployment
            sudo kubectl get service
      - run:
          command: |
            KUBEDNS=`sudo kubectl get svc -o json kube-dns --namespace=kube-system | jq -r '.spec.clusterIP'`
            echo "nameserver $KUBEDNS" | sudo tee -a /etc/resolvconf/resolv.conf.d/head > /dev/null
            echo "search default.svc.cluster.local svc.cluster.local cluster.local" | sudo tee -a /etc/resolvconf/resolv.conf.d/base > /dev/null
            echo "options ndots:5" | sudo tee -a /etc/resolvconf/resolv.conf.d/base > /dev/null
            sudo resolvconf -u
      - run:
          command: |
            nslookup circleci-example.default
            curl circleci-example.default
      - restore_cache:
          keys:
            - miniconda-v1-{{ checksum "ci/environment-3.7.yml" }}
      - run:
          name: install miniconda
          command: |
            if [ ! -d "/home/circleci/miniconda" ]; then
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              bash miniconda.sh -b -p $HOME/miniconda
              export PATH="$HOME/miniconda/bin:$PATH"
              conda config --set always_yes yes --set changeps1 no
            fi
            sudo chown -R $USER.$USER $HOME
      - run:
          name: configure conda
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            if [ ! -d "/home/circleci/miniconda/envs/dask-kubernetes-test" ]; then
              conda update -q conda
              conda env create -f ci/environment-${PYTHON}.yml --name=${ENV_NAME}
              source activate ${ENV_NAME}
              pip install --no-deps --quiet -e .
            fi
            conda env list
            conda list ${ENV_NAME}
      - save_cache:
          key: miniconda-v1-{{ checksum "ci/environment-3.7.yml" }}
          paths:
            - "/home/circleci/miniconda"
      - run:
          name: build docker
          command: |
            # eval $(minikube docker-env)
            docker build -t daskdev/dask:dev docker/
      - run:
          command: |
            # eval $(minikube docker-env)
            /home/circleci/miniconda/envs/dask-kubernetes-test/bin/py.test dask_kubernetes -s --verbose --worker-image daskdev/dask:dev
      - run:
          command: |
            /home/circleci/miniconda/envs/dask-kubernetes-test/bin/flake8 dask-kubernetes
            /home/circleci/miniconda/envs/dask-kubernetes-test/bin/black --check dask_kubernetes setup.py
