name: dask-kubernetes-test
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - nomkl
  - pip
  # testing / CI
  - flake8
  - ipywidgets
  - pytest
  - black
  - pyyaml
  # dask dependencies
  - cloudpickle
  - toolz
  - cytoolz
  - numpy
  - partd
  # distributed dependencies
  - click >=6.6
  - msgpack-python
  - psutil >=5.0
  - six
  - sortedcontainers !=2.0.0,!=2.0.1
  - tblib
  - tornado >=5
  - zict >=0.1.3
  - pip:
    - kubernetes==9
    - git+https://github.com/dask/dask
    - git+https://github.com/dask/distributed
