name: dask-kubernetes-test
channels:
  - defaults
dependencies:
  - flake8
  - ipywidgets
  - dask=0.19.4
  - distributed=1.23.3
  - nomkl
  - pytest
  - python=3.6
  - pyyaml
  - pip:
    - kubernetes==9
