name: dask-kubernetes-test
channels:
  - defaults
dependencies:
  - flake8
  - ipywidgets
  - distributed=1.21.3
  - dask=0.17.1
  - nomkl
  - pytest
  - python=3.6
  - pyyaml
  - pip:
    - kubernetes==4
